/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v9.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 9.0.1
board: MIMXRT1020-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 6b13ed20-900a-476a-a8a1-f8785f498fa3
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * ENC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ENC1'
- type: 'enc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'enc_a31ae546b0cbfc3aa2c35851e1fcb3b8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ENC1'
- config_sets:
  - fsl_enc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - decoderWorkMode: 'kENC_DecoderWorkAsNormalMode'
      - enableReverseDirection: 'false'
      - posInitialization:
        - HOMETriggerMode: 'kENC_HOMETriggerDisabled'
        - INDEXTriggerMode: 'kENC_INDEXTriggerDisabled'
        - positionInitialValue: '0'
      - triggerAction: ''
      - positionMatchConfig:
        - positionMatchMode: 'kENC_POSMATCHOnPositionCounterEqualToComapreValue'
        - positionCompareValue: '0xFFFFFFFF'
      - modulusConfig:
        - revolutionCountCondition: 'kENC_RevolutionCountOnINDEXPulse'
        - enableModuloCountMode: 'false'
      - wdogConfig:
        - enableWatchdog: 'false'
      - filter_config_t:
        - enableFilter: 'false'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_home_irq: 'false'
      - interrupt_home:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_wdog_irq: 'false'
      - interrupt_wdog:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
      - enable_index_irq: 'false'
      - interrupt_index:
        - IRQn: 'ENC1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ENC configuration */
enc_config_t ENC1_config = {
  .decoderWorkMode = kENC_DecoderWorkAsNormalMode,
  .enableReverseDirection = false,
  .HOMETriggerMode = kENC_HOMETriggerDisabled,
  .INDEXTriggerMode = kENC_INDEXTriggerDisabled,
  .positionInitialValue = 0,
  .enableTRIGGERClearPositionCounter = false,
  .enableTRIGGERClearHoldPositionCounter = false,
  .positionMatchMode = kENC_POSMATCHOnPositionCounterEqualToComapreValue,
  .positionCompareValue = 4294967295,
  .revolutionCountCondition = kENC_RevolutionCountOnINDEXPulse,
  .enableModuloCountMode = false,
  .positionModulusValue = 0,
  .enableWatchdog = false,
  .watchdogTimeoutValue = 0,
  .filterCount = 0,
  .filterSamplePeriod = 0
};

static void ENC1_init(void) {
  /* ENC initialization */
  ENC_Init(ENC1_PERIPHERAL, &ENC1_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  ENC1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
