/*
 * Copyright 2018-2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_05 (number 106), JTAG_nTRST/J16[3]/USER_LED/J17[5] */
/* Routed pin properties */
#define BOARD_INITPINS_ENC_SW_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ENC_SW_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ENC_SW_CHANNEL                                         5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ENC_SW_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ENC_SW_GPIO_PIN                                        5U   /*!< GPIO pin number */
#define BOARD_INITPINS_ENC_SW_GPIO_PIN_MASK                           (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ENC_SW_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ENC_SW_PIN                                             5U   /*!< PORT pin number */
#define BOARD_INITPINS_ENC_SW_PIN_MASK                                (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B1_12 (number 78), USB_OTG1_OC/J18[3] */
/* Routed pin properties */
#define BOARD_INITPINS_TFT_SCL_PERIPHERAL                                 LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_TFT_SCL_SIGNAL                                        SCK   /*!< Signal name */

/* GPIO_AD_B1_13 (number 76), CAN_STBY/J18[4] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN_STBY_PERIPHERAL                                LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_CAN_STBY_SIGNAL                                      PCS0   /*!< Signal name */

/* GPIO_AD_B1_14 (number 75), I2C1_SCL/U10[17]/J18[6] */
/* Routed pin properties */
#define BOARD_INITPINS_TFT_DA_PERIPHERAL                                  LPSPI3   /*!< Peripheral name */
#define BOARD_INITPINS_TFT_DA_SIGNAL                                         SDO   /*!< Signal name */

/* GPIO_AD_B1_10 (number 80), USB_OTG1_PWR/J18[1] */
/* Routed pin properties */
#define BOARD_INITPINS_TFT_DC_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_TFT_DC_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TFT_DC_CHANNEL                                        26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TFT_DC_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TFT_DC_GPIO_PIN                                       26U   /*!< GPIO pin number */
#define BOARD_INITPINS_TFT_DC_GPIO_PIN_MASK                          (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TFT_DC_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TFT_DC_PIN                                            26U   /*!< PORT pin number */
#define BOARD_INITPINS_TFT_DC_PIN_MASK                               (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (number 79), USB_OTG1_ID/J18[2] */
/* Routed pin properties */
#define BOARD_INITPINS_TFT_RES_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_TFT_RES_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TFT_RES_CHANNEL                                       27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TFT_RES_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TFT_RES_GPIO_PIN                                      27U   /*!< GPIO pin number */
#define BOARD_INITPINS_TFT_RES_GPIO_PIN_MASK                         (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TFT_RES_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TFT_RES_PIN                                           27U   /*!< PORT pin number */
#define BOARD_INITPINS_TFT_RES_PIN_MASK                              (1U << 27U)   /*!< PORT pin mask */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DHT_GPIO_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DHT_GPIO_GPIO_PIN                                     29U   /*!< GPIO pin number */
#define BOARD_INITPINS_DHT_GPIO_GPIO_PIN_MASK                        (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DHT_GPIO_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DHT_GPIO_PIN                                          29U   /*!< PORT pin number */
#define BOARD_INITPINS_DHT_GPIO_PIN_MASK                             (1U << 29U)   /*!< PORT pin mask */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_COB_GPIO_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_COB_GPIO_GPIO_PIN                                     31U   /*!< GPIO pin number */
#define BOARD_INITPINS_COB_GPIO_GPIO_PIN_MASK                        (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_COB_GPIO_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_COB_GPIO_PIN                                          31U   /*!< PORT pin number */
#define BOARD_INITPINS_COB_GPIO_PIN_MASK                             (1U << 31U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define LPSPI1_INITPINS_ENET_RXD0_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define LPSPI1_INITPINS_ENET_RXD0_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[3] */
/* Routed pin properties */
#define LPSPI1_INITPINS_ENET_CRS_DV_PERIPHERAL                            LPSPI1   /*!< Peripheral name */
#define LPSPI1_INITPINS_ENET_CRS_DV_SIGNAL                                  PCS0   /*!< Signal name */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define LPSPI1_INITPINS_ENET_RXER_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define LPSPI1_INITPINS_ENET_RXER_SIGNAL                                     SDO   /*!< Signal name */

/* GPIO_AD_B0_13 (number 95), ENET_TXEN/U11[23]/J19[5] */
/* Routed pin properties */
#define LPSPI1_INITPINS_ENET_TXEN_PERIPHERAL                              LPSPI1   /*!< Peripheral name */
#define LPSPI1_INITPINS_ENET_TXEN_SIGNAL                                     SDI   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_InitPins(void);

/* GPIO_AD_B0_10 (number 98), ENET_RXD0/U11[16]/J19[6] */
/* Routed pin properties */
#define LPSPI1_DEINITPINS_ENET_RXD0_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define LPSPI1_DEINITPINS_ENET_RXD0_SIGNAL                               gpio_io   /*!< Signal name */
#define LPSPI1_DEINITPINS_ENET_RXD0_CHANNEL                                  10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_ENET_RXD0_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_RXD0_GPIO_PIN                                 10U   /*!< GPIO pin number */
#define LPSPI1_DEINITPINS_ENET_RXD0_GPIO_PIN_MASK                    (1U << 10U)   /*!< GPIO pin mask */
#define LPSPI1_DEINITPINS_ENET_RXD0_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_RXD0_PIN                                      10U   /*!< PORT pin number */
#define LPSPI1_DEINITPINS_ENET_RXD0_PIN_MASK                         (1U << 10U)   /*!< PORT pin mask */

/* GPIO_AD_B0_11 (number 97), ENET_CRS_DV/U11[18]/J19[3] */
/* Routed pin properties */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_PERIPHERAL                           GPIO1   /*!< Peripheral name */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_SIGNAL                             gpio_io   /*!< Signal name */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_CHANNEL                                11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_GPIO                                 GPIO1   /*!< GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_GPIO_PIN                               11U   /*!< GPIO pin number */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_GPIO_PIN_MASK                  (1U << 11U)   /*!< GPIO pin mask */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_PORT                                 GPIO1   /*!< PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_PIN                                    11U   /*!< PORT pin number */
#define LPSPI1_DEINITPINS_ENET_CRS_DV_PIN_MASK                       (1U << 11U)   /*!< PORT pin mask */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define LPSPI1_DEINITPINS_ENET_RXER_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define LPSPI1_DEINITPINS_ENET_RXER_SIGNAL                               gpio_io   /*!< Signal name */
#define LPSPI1_DEINITPINS_ENET_RXER_CHANNEL                                  12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_ENET_RXER_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_RXER_GPIO_PIN                                 12U   /*!< GPIO pin number */
#define LPSPI1_DEINITPINS_ENET_RXER_GPIO_PIN_MASK                    (1U << 12U)   /*!< GPIO pin mask */
#define LPSPI1_DEINITPINS_ENET_RXER_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_RXER_PIN                                      12U   /*!< PORT pin number */
#define LPSPI1_DEINITPINS_ENET_RXER_PIN_MASK                         (1U << 12U)   /*!< PORT pin mask */

/* GPIO_AD_B0_13 (number 95), ENET_TXEN/U11[23]/J19[5] */
/* Routed pin properties */
#define LPSPI1_DEINITPINS_ENET_TXEN_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define LPSPI1_DEINITPINS_ENET_TXEN_SIGNAL                               gpio_io   /*!< Signal name */
#define LPSPI1_DEINITPINS_ENET_TXEN_CHANNEL                                  13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_ENET_TXEN_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_TXEN_GPIO_PIN                                 13U   /*!< GPIO pin number */
#define LPSPI1_DEINITPINS_ENET_TXEN_GPIO_PIN_MASK                    (1U << 13U)   /*!< GPIO pin mask */
#define LPSPI1_DEINITPINS_ENET_TXEN_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_ENET_TXEN_PIN                                      13U   /*!< PORT pin number */
#define LPSPI1_DEINITPINS_ENET_TXEN_PIN_MASK                         (1U << 13U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_DeinitPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPI2C4_InitPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPI2C4_DeinitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI3_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI3_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
